// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plume/sample/unity/settings/audio_settings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PLUME.Sample.Unity.Settings {

  /// <summary>Holder for reflection information generated from plume/sample/unity/settings/audio_settings.proto</summary>
  public static partial class AudioSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for plume/sample/unity/settings/audio_settings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudioSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBwbHVtZS9zYW1wbGUvdW5pdHkvc2V0dGluZ3MvYXVkaW9fc2V0dGluZ3Mu",
            "cHJvdG8SG3BsdW1lLnNhbXBsZS51bml0eS5zZXR0aW5ncyLRAQoTQXVkaW9T",
            "ZXR0aW5nc1VwZGF0ZRJQCgxzcGVha2VyX21vZGUYASABKA4yKC5wbHVtZS5z",
            "YW1wbGUudW5pdHkuc2V0dGluZ3MuU3BlYWtlck1vZGVIAFILc3BlYWtlck1v",
            "ZGWIAQESOwoXc3BhdGlhbGl6ZXJfcGx1Z2luX25hbWUYAiABKAlIAVIVc3Bh",
            "dGlhbGl6ZXJQbHVnaW5OYW1liAEBQg8KDV9zcGVha2VyX21vZGVCGgoYX3Nw",
            "YXRpYWxpemVyX3BsdWdpbl9uYW1lKtABCgtTcGVha2VyTW9kZRIVChFTUEVB",
            "S0VSX01PREVfTU9OTxAAEhcKE1NQRUFLRVJfTU9ERV9TVEVSRU8QARIVChFT",
            "UEVBS0VSX01PREVfUVVBRBACEhkKFVNQRUFLRVJfTU9ERV9TVVJST1VORBAD",
            "EiEKHVNQRUFLRVJfTU9ERV9TVVJST1VORF81UE9JTlQxEAQSIQodU1BFQUtF",
            "Ul9NT0RFX1NVUlJPVU5EXzdQT0lOVDEQBRIZChVTUEVBS0VSX01PREVfUFJP",
            "TE9HSUMQBkIeqgIbUExVTUUuU2FtcGxlLlVuaXR5LlNldHRpbmdzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PLUME.Sample.Unity.Settings.SpeakerMode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.Settings.AudioSettingsUpdate), global::PLUME.Sample.Unity.Settings.AudioSettingsUpdate.Parser, new[]{ "SpeakerMode", "SpatializerPluginName" }, new[]{ "SpeakerMode", "SpatializerPluginName" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum SpeakerMode {
    [pbr::OriginalName("SPEAKER_MODE_MONO")] Mono = 0,
    [pbr::OriginalName("SPEAKER_MODE_STEREO")] Stereo = 1,
    [pbr::OriginalName("SPEAKER_MODE_QUAD")] Quad = 2,
    [pbr::OriginalName("SPEAKER_MODE_SURROUND")] Surround = 3,
    [pbr::OriginalName("SPEAKER_MODE_SURROUND_5POINT1")] Surround5Point1 = 4,
    [pbr::OriginalName("SPEAKER_MODE_SURROUND_7POINT1")] Surround7Point1 = 5,
    [pbr::OriginalName("SPEAKER_MODE_PROLOGIC")] Prologic = 6,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Corresponds to the properties of a quality level defined in Project Settings > Audio
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioSettingsUpdate : pb::IMessage<AudioSettingsUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioSettingsUpdate> _parser = new pb::MessageParser<AudioSettingsUpdate>(() => new AudioSettingsUpdate());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioSettingsUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.Settings.AudioSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioSettingsUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioSettingsUpdate(AudioSettingsUpdate other) : this() {
      _hasBits0 = other._hasBits0;
      speakerMode_ = other.speakerMode_;
      spatializerPluginName_ = other.spatializerPluginName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioSettingsUpdate Clone() {
      return new AudioSettingsUpdate(this);
    }

    /// <summary>Field number for the "speaker_mode" field.</summary>
    public const int SpeakerModeFieldNumber = 1;
    private readonly static global::PLUME.Sample.Unity.Settings.SpeakerMode SpeakerModeDefaultValue = global::PLUME.Sample.Unity.Settings.SpeakerMode.Mono;

    private global::PLUME.Sample.Unity.Settings.SpeakerMode speakerMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.Settings.SpeakerMode SpeakerMode {
      get { if ((_hasBits0 & 1) != 0) { return speakerMode_; } else { return SpeakerModeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        speakerMode_ = value;
      }
    }
    /// <summary>Gets whether the "speaker_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSpeakerMode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "speaker_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSpeakerMode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "spatializer_plugin_name" field.</summary>
    public const int SpatializerPluginNameFieldNumber = 2;
    private readonly static string SpatializerPluginNameDefaultValue = "";

    private string spatializerPluginName_;
    /// <summary>
    /// TODO: Add more properties (ie. global volume, doppler factor, etc.)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SpatializerPluginName {
      get { return spatializerPluginName_ ?? SpatializerPluginNameDefaultValue; }
      set {
        spatializerPluginName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "spatializer_plugin_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSpatializerPluginName {
      get { return spatializerPluginName_ != null; }
    }
    /// <summary>Clears the value of the "spatializer_plugin_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSpatializerPluginName() {
      spatializerPluginName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioSettingsUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioSettingsUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpeakerMode != other.SpeakerMode) return false;
      if (SpatializerPluginName != other.SpatializerPluginName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSpeakerMode) hash ^= SpeakerMode.GetHashCode();
      if (HasSpatializerPluginName) hash ^= SpatializerPluginName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSpeakerMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SpeakerMode);
      }
      if (HasSpatializerPluginName) {
        output.WriteRawTag(18);
        output.WriteString(SpatializerPluginName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSpeakerMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SpeakerMode);
      }
      if (HasSpatializerPluginName) {
        output.WriteRawTag(18);
        output.WriteString(SpatializerPluginName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSpeakerMode) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SpeakerMode);
      }
      if (HasSpatializerPluginName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpatializerPluginName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioSettingsUpdate other) {
      if (other == null) {
        return;
      }
      if (other.HasSpeakerMode) {
        SpeakerMode = other.SpeakerMode;
      }
      if (other.HasSpatializerPluginName) {
        SpatializerPluginName = other.SpatializerPluginName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpeakerMode = (global::PLUME.Sample.Unity.Settings.SpeakerMode) input.ReadEnum();
            break;
          }
          case 18: {
            SpatializerPluginName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpeakerMode = (global::PLUME.Sample.Unity.Settings.SpeakerMode) input.ReadEnum();
            break;
          }
          case 18: {
            SpatializerPluginName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
