// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plume/sample/unity/ui/rect_transform.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PLUME.Sample.Unity.UI {

  /// <summary>Holder for reflection information generated from plume/sample/unity/ui/rect_transform.proto</summary>
  public static partial class RectTransformReflection {

    #region Descriptor
    /// <summary>File descriptor for plume/sample/unity/ui/rect_transform.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RectTransformReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipwbHVtZS9zYW1wbGUvdW5pdHkvdWkvcmVjdF90cmFuc2Zvcm0ucHJvdG8S",
            "FXBsdW1lLnNhbXBsZS51bml0eS51aRohcGx1bWUvc2FtcGxlL2NvbW1vbi92",
            "ZWN0b3IzLnByb3RvGiRwbHVtZS9zYW1wbGUvY29tbW9uL3F1YXRlcm5pb24u",
            "cHJvdG8aIXBsdW1lL3NhbXBsZS9jb21tb24vdmVjdG9yMi5wcm90bxokcGx1",
            "bWUvc2FtcGxlL3VuaXR5L2lkZW50aWZpZXJzLnByb3RvIlwKE1JlY3RUcmFu",
            "c2Zvcm1DcmVhdGUSRQoJY29tcG9uZW50GAEgASgLMicucGx1bWUuc2FtcGxl",
            "LnVuaXR5LkNvbXBvbmVudElkZW50aWZpZXJSCWNvbXBvbmVudCJdChRSZWN0",
            "VHJhbnNmb3JtRGVzdHJveRJFCgljb21wb25lbnQYASABKAsyJy5wbHVtZS5z",
            "YW1wbGUudW5pdHkuQ29tcG9uZW50SWRlbnRpZmllclIJY29tcG9uZW50Iq0H",
            "ChNSZWN0VHJhbnNmb3JtVXBkYXRlEkUKCWNvbXBvbmVudBgBIAEoCzInLnBs",
            "dW1lLnNhbXBsZS51bml0eS5Db21wb25lbnRJZGVudGlmaWVyUgljb21wb25l",
            "bnQSVwoQcGFyZW50X3RyYW5zZm9ybRgCIAEoCzInLnBsdW1lLnNhbXBsZS51",
            "bml0eS5Db21wb25lbnRJZGVudGlmaWVySABSD3BhcmVudFRyYW5zZm9ybYgB",
            "ARIkCgtzaWJsaW5nX2lkeBgDIAEoBUgBUgpzaWJsaW5nSWR4iAEBEkgKDmxv",
            "Y2FsX3Bvc2l0aW9uGAQgASgLMhwucGx1bWUuc2FtcGxlLmNvbW1vbi5WZWN0",
            "b3IzSAJSDWxvY2FsUG9zaXRpb26IAQESSwoObG9jYWxfcm90YXRpb24YBSAB",
            "KAsyHy5wbHVtZS5zYW1wbGUuY29tbW9uLlF1YXRlcm5pb25IA1INbG9jYWxS",
            "b3RhdGlvbogBARJCCgtsb2NhbF9zY2FsZRgGIAEoCzIcLnBsdW1lLnNhbXBs",
            "ZS5jb21tb24uVmVjdG9yM0gEUgpsb2NhbFNjYWxliAEBEkAKCmFuY2hvcl9t",
            "aW4YByABKAsyHC5wbHVtZS5zYW1wbGUuY29tbW9uLlZlY3RvcjJIBVIJYW5j",
            "aG9yTWluiAEBEkAKCmFuY2hvcl9tYXgYCCABKAsyHC5wbHVtZS5zYW1wbGUu",
            "Y29tbW9uLlZlY3RvcjJIBlIJYW5jaG9yTWF4iAEBEk4KEWFuY2hvcmVkX3Bv",
            "c2l0aW9uGAkgASgLMhwucGx1bWUuc2FtcGxlLmNvbW1vbi5WZWN0b3IySAdS",
            "EGFuY2hvcmVkUG9zaXRpb26IAQESQAoKc2l6ZV9kZWx0YRgKIAEoCzIcLnBs",
            "dW1lLnNhbXBsZS5jb21tb24uVmVjdG9yMkgIUglzaXplRGVsdGGIAQESNwoF",
            "cGl2b3QYCyABKAsyHC5wbHVtZS5zYW1wbGUuY29tbW9uLlZlY3RvcjJICVIF",
            "cGl2b3SIAQFCEwoRX3BhcmVudF90cmFuc2Zvcm1CDgoMX3NpYmxpbmdfaWR4",
            "QhEKD19sb2NhbF9wb3NpdGlvbkIRCg9fbG9jYWxfcm90YXRpb25CDgoMX2xv",
            "Y2FsX3NjYWxlQg0KC19hbmNob3JfbWluQg0KC19hbmNob3JfbWF4QhQKEl9h",
            "bmNob3JlZF9wb3NpdGlvbkINCgtfc2l6ZV9kZWx0YUIICgZfcGl2b3RCGKoC",
            "FVBMVU1FLlNhbXBsZS5Vbml0eS5VSWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PLUME.Sample.Common.Vector3Reflection.Descriptor, global::PLUME.Sample.Common.QuaternionReflection.Descriptor, global::PLUME.Sample.Common.Vector2Reflection.Descriptor, global::PLUME.Sample.Unity.IdentifiersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.UI.RectTransformCreate), global::PLUME.Sample.Unity.UI.RectTransformCreate.Parser, new[]{ "Component" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.UI.RectTransformDestroy), global::PLUME.Sample.Unity.UI.RectTransformDestroy.Parser, new[]{ "Component" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.UI.RectTransformUpdate), global::PLUME.Sample.Unity.UI.RectTransformUpdate.Parser, new[]{ "Component", "ParentTransform", "SiblingIdx", "LocalPosition", "LocalRotation", "LocalScale", "AnchorMin", "AnchorMax", "AnchoredPosition", "SizeDelta", "Pivot" }, new[]{ "ParentTransform", "SiblingIdx", "LocalPosition", "LocalRotation", "LocalScale", "AnchorMin", "AnchorMax", "AnchoredPosition", "SizeDelta", "Pivot" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RectTransformCreate : pb::IMessage<RectTransformCreate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RectTransformCreate> _parser = new pb::MessageParser<RectTransformCreate>(() => new RectTransformCreate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RectTransformCreate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.UI.RectTransformReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformCreate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformCreate(RectTransformCreate other) : this() {
      component_ = other.component_ != null ? other.component_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformCreate Clone() {
      return new RectTransformCreate(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RectTransformCreate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RectTransformCreate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RectTransformCreate other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RectTransformDestroy : pb::IMessage<RectTransformDestroy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RectTransformDestroy> _parser = new pb::MessageParser<RectTransformDestroy>(() => new RectTransformDestroy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RectTransformDestroy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.UI.RectTransformReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformDestroy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformDestroy(RectTransformDestroy other) : this() {
      component_ = other.component_ != null ? other.component_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformDestroy Clone() {
      return new RectTransformDestroy(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RectTransformDestroy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RectTransformDestroy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RectTransformDestroy other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RectTransformUpdate : pb::IMessage<RectTransformUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RectTransformUpdate> _parser = new pb::MessageParser<RectTransformUpdate>(() => new RectTransformUpdate());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RectTransformUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.UI.RectTransformReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformUpdate(RectTransformUpdate other) : this() {
      _hasBits0 = other._hasBits0;
      component_ = other.component_ != null ? other.component_.Clone() : null;
      parentTransform_ = other.parentTransform_ != null ? other.parentTransform_.Clone() : null;
      siblingIdx_ = other.siblingIdx_;
      localPosition_ = other.localPosition_ != null ? other.localPosition_.Clone() : null;
      localRotation_ = other.localRotation_ != null ? other.localRotation_.Clone() : null;
      localScale_ = other.localScale_ != null ? other.localScale_.Clone() : null;
      anchorMin_ = other.anchorMin_ != null ? other.anchorMin_.Clone() : null;
      anchorMax_ = other.anchorMax_ != null ? other.anchorMax_.Clone() : null;
      anchoredPosition_ = other.anchoredPosition_ != null ? other.anchoredPosition_.Clone() : null;
      sizeDelta_ = other.sizeDelta_ != null ? other.sizeDelta_.Clone() : null;
      pivot_ = other.pivot_ != null ? other.pivot_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectTransformUpdate Clone() {
      return new RectTransformUpdate(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    /// <summary>Field number for the "parent_transform" field.</summary>
    public const int ParentTransformFieldNumber = 2;
    private global::PLUME.Sample.Unity.ComponentIdentifier parentTransform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier ParentTransform {
      get { return parentTransform_; }
      set {
        parentTransform_ = value;
      }
    }

    /// <summary>Field number for the "sibling_idx" field.</summary>
    public const int SiblingIdxFieldNumber = 3;
    private readonly static int SiblingIdxDefaultValue = 0;

    private int siblingIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SiblingIdx {
      get { if ((_hasBits0 & 1) != 0) { return siblingIdx_; } else { return SiblingIdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        siblingIdx_ = value;
      }
    }
    /// <summary>Gets whether the "sibling_idx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSiblingIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "sibling_idx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSiblingIdx() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "local_position" field.</summary>
    public const int LocalPositionFieldNumber = 4;
    private global::PLUME.Sample.Common.Vector3 localPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector3 LocalPosition {
      get { return localPosition_; }
      set {
        localPosition_ = value;
      }
    }

    /// <summary>Field number for the "local_rotation" field.</summary>
    public const int LocalRotationFieldNumber = 5;
    private global::PLUME.Sample.Common.Quaternion localRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Quaternion LocalRotation {
      get { return localRotation_; }
      set {
        localRotation_ = value;
      }
    }

    /// <summary>Field number for the "local_scale" field.</summary>
    public const int LocalScaleFieldNumber = 6;
    private global::PLUME.Sample.Common.Vector3 localScale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector3 LocalScale {
      get { return localScale_; }
      set {
        localScale_ = value;
      }
    }

    /// <summary>Field number for the "anchor_min" field.</summary>
    public const int AnchorMinFieldNumber = 7;
    private global::PLUME.Sample.Common.Vector2 anchorMin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector2 AnchorMin {
      get { return anchorMin_; }
      set {
        anchorMin_ = value;
      }
    }

    /// <summary>Field number for the "anchor_max" field.</summary>
    public const int AnchorMaxFieldNumber = 8;
    private global::PLUME.Sample.Common.Vector2 anchorMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector2 AnchorMax {
      get { return anchorMax_; }
      set {
        anchorMax_ = value;
      }
    }

    /// <summary>Field number for the "anchored_position" field.</summary>
    public const int AnchoredPositionFieldNumber = 9;
    private global::PLUME.Sample.Common.Vector2 anchoredPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector2 AnchoredPosition {
      get { return anchoredPosition_; }
      set {
        anchoredPosition_ = value;
      }
    }

    /// <summary>Field number for the "size_delta" field.</summary>
    public const int SizeDeltaFieldNumber = 10;
    private global::PLUME.Sample.Common.Vector2 sizeDelta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector2 SizeDelta {
      get { return sizeDelta_; }
      set {
        sizeDelta_ = value;
      }
    }

    /// <summary>Field number for the "pivot" field.</summary>
    public const int PivotFieldNumber = 11;
    private global::PLUME.Sample.Common.Vector2 pivot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Vector2 Pivot {
      get { return pivot_; }
      set {
        pivot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RectTransformUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RectTransformUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      if (!object.Equals(ParentTransform, other.ParentTransform)) return false;
      if (SiblingIdx != other.SiblingIdx) return false;
      if (!object.Equals(LocalPosition, other.LocalPosition)) return false;
      if (!object.Equals(LocalRotation, other.LocalRotation)) return false;
      if (!object.Equals(LocalScale, other.LocalScale)) return false;
      if (!object.Equals(AnchorMin, other.AnchorMin)) return false;
      if (!object.Equals(AnchorMax, other.AnchorMax)) return false;
      if (!object.Equals(AnchoredPosition, other.AnchoredPosition)) return false;
      if (!object.Equals(SizeDelta, other.SizeDelta)) return false;
      if (!object.Equals(Pivot, other.Pivot)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (parentTransform_ != null) hash ^= ParentTransform.GetHashCode();
      if (HasSiblingIdx) hash ^= SiblingIdx.GetHashCode();
      if (localPosition_ != null) hash ^= LocalPosition.GetHashCode();
      if (localRotation_ != null) hash ^= LocalRotation.GetHashCode();
      if (localScale_ != null) hash ^= LocalScale.GetHashCode();
      if (anchorMin_ != null) hash ^= AnchorMin.GetHashCode();
      if (anchorMax_ != null) hash ^= AnchorMax.GetHashCode();
      if (anchoredPosition_ != null) hash ^= AnchoredPosition.GetHashCode();
      if (sizeDelta_ != null) hash ^= SizeDelta.GetHashCode();
      if (pivot_ != null) hash ^= Pivot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (parentTransform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ParentTransform);
      }
      if (HasSiblingIdx) {
        output.WriteRawTag(24);
        output.WriteInt32(SiblingIdx);
      }
      if (localPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalPosition);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LocalRotation);
      }
      if (localScale_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LocalScale);
      }
      if (anchorMin_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(AnchorMin);
      }
      if (anchorMax_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(AnchorMax);
      }
      if (anchoredPosition_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(AnchoredPosition);
      }
      if (sizeDelta_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(SizeDelta);
      }
      if (pivot_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Pivot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (parentTransform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ParentTransform);
      }
      if (HasSiblingIdx) {
        output.WriteRawTag(24);
        output.WriteInt32(SiblingIdx);
      }
      if (localPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalPosition);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LocalRotation);
      }
      if (localScale_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LocalScale);
      }
      if (anchorMin_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(AnchorMin);
      }
      if (anchorMax_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(AnchorMax);
      }
      if (anchoredPosition_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(AnchoredPosition);
      }
      if (sizeDelta_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(SizeDelta);
      }
      if (pivot_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Pivot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (parentTransform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParentTransform);
      }
      if (HasSiblingIdx) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SiblingIdx);
      }
      if (localPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalPosition);
      }
      if (localRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalRotation);
      }
      if (localScale_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalScale);
      }
      if (anchorMin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnchorMin);
      }
      if (anchorMax_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnchorMax);
      }
      if (anchoredPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnchoredPosition);
      }
      if (sizeDelta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SizeDelta);
      }
      if (pivot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pivot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RectTransformUpdate other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      if (other.parentTransform_ != null) {
        if (parentTransform_ == null) {
          ParentTransform = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        ParentTransform.MergeFrom(other.ParentTransform);
      }
      if (other.HasSiblingIdx) {
        SiblingIdx = other.SiblingIdx;
      }
      if (other.localPosition_ != null) {
        if (localPosition_ == null) {
          LocalPosition = new global::PLUME.Sample.Common.Vector3();
        }
        LocalPosition.MergeFrom(other.LocalPosition);
      }
      if (other.localRotation_ != null) {
        if (localRotation_ == null) {
          LocalRotation = new global::PLUME.Sample.Common.Quaternion();
        }
        LocalRotation.MergeFrom(other.LocalRotation);
      }
      if (other.localScale_ != null) {
        if (localScale_ == null) {
          LocalScale = new global::PLUME.Sample.Common.Vector3();
        }
        LocalScale.MergeFrom(other.LocalScale);
      }
      if (other.anchorMin_ != null) {
        if (anchorMin_ == null) {
          AnchorMin = new global::PLUME.Sample.Common.Vector2();
        }
        AnchorMin.MergeFrom(other.AnchorMin);
      }
      if (other.anchorMax_ != null) {
        if (anchorMax_ == null) {
          AnchorMax = new global::PLUME.Sample.Common.Vector2();
        }
        AnchorMax.MergeFrom(other.AnchorMax);
      }
      if (other.anchoredPosition_ != null) {
        if (anchoredPosition_ == null) {
          AnchoredPosition = new global::PLUME.Sample.Common.Vector2();
        }
        AnchoredPosition.MergeFrom(other.AnchoredPosition);
      }
      if (other.sizeDelta_ != null) {
        if (sizeDelta_ == null) {
          SizeDelta = new global::PLUME.Sample.Common.Vector2();
        }
        SizeDelta.MergeFrom(other.SizeDelta);
      }
      if (other.pivot_ != null) {
        if (pivot_ == null) {
          Pivot = new global::PLUME.Sample.Common.Vector2();
        }
        Pivot.MergeFrom(other.Pivot);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
          case 18: {
            if (parentTransform_ == null) {
              ParentTransform = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(ParentTransform);
            break;
          }
          case 24: {
            SiblingIdx = input.ReadInt32();
            break;
          }
          case 34: {
            if (localPosition_ == null) {
              LocalPosition = new global::PLUME.Sample.Common.Vector3();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
          case 42: {
            if (localRotation_ == null) {
              LocalRotation = new global::PLUME.Sample.Common.Quaternion();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 50: {
            if (localScale_ == null) {
              LocalScale = new global::PLUME.Sample.Common.Vector3();
            }
            input.ReadMessage(LocalScale);
            break;
          }
          case 58: {
            if (anchorMin_ == null) {
              AnchorMin = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchorMin);
            break;
          }
          case 66: {
            if (anchorMax_ == null) {
              AnchorMax = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchorMax);
            break;
          }
          case 74: {
            if (anchoredPosition_ == null) {
              AnchoredPosition = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchoredPosition);
            break;
          }
          case 82: {
            if (sizeDelta_ == null) {
              SizeDelta = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(SizeDelta);
            break;
          }
          case 90: {
            if (pivot_ == null) {
              Pivot = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(Pivot);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
          case 18: {
            if (parentTransform_ == null) {
              ParentTransform = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(ParentTransform);
            break;
          }
          case 24: {
            SiblingIdx = input.ReadInt32();
            break;
          }
          case 34: {
            if (localPosition_ == null) {
              LocalPosition = new global::PLUME.Sample.Common.Vector3();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
          case 42: {
            if (localRotation_ == null) {
              LocalRotation = new global::PLUME.Sample.Common.Quaternion();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 50: {
            if (localScale_ == null) {
              LocalScale = new global::PLUME.Sample.Common.Vector3();
            }
            input.ReadMessage(LocalScale);
            break;
          }
          case 58: {
            if (anchorMin_ == null) {
              AnchorMin = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchorMin);
            break;
          }
          case 66: {
            if (anchorMax_ == null) {
              AnchorMax = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchorMax);
            break;
          }
          case 74: {
            if (anchoredPosition_ == null) {
              AnchoredPosition = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(AnchoredPosition);
            break;
          }
          case 82: {
            if (sizeDelta_ == null) {
              SizeDelta = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(SizeDelta);
            break;
          }
          case 90: {
            if (pivot_ == null) {
              Pivot = new global::PLUME.Sample.Common.Vector2();
            }
            input.ReadMessage(Pivot);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
