// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plume/sample/unity/hdrp/additional_light_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PLUME.Sample.Unity.HDRP {

  /// <summary>Holder for reflection information generated from plume/sample/unity/hdrp/additional_light_data.proto</summary>
  public static partial class AdditionalLightDataReflection {

    #region Descriptor
    /// <summary>File descriptor for plume/sample/unity/hdrp/additional_light_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdditionalLightDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNwbHVtZS9zYW1wbGUvdW5pdHkvaGRycC9hZGRpdGlvbmFsX2xpZ2h0X2Rh",
            "dGEucHJvdG8SF3BsdW1lLnNhbXBsZS51bml0eS5oZHJwGiRwbHVtZS9zYW1w",
            "bGUvdW5pdHkvaWRlbnRpZmllcnMucHJvdG8aH3BsdW1lL3NhbXBsZS9jb21t",
            "b24vY29sb3IucHJvdG8iZAobSERBZGRpdGlvbmFsTGlnaHREYXRhQ3JlYXRl",
            "EkUKCWNvbXBvbmVudBgBIAEoCzInLnBsdW1lLnNhbXBsZS51bml0eS5Db21w",
            "b25lbnRJZGVudGlmaWVyUgljb21wb25lbnQiZQocSERBZGRpdGlvbmFsTGln",
            "aHREYXRhRGVzdHJveRJFCgljb21wb25lbnQYASABKAsyJy5wbHVtZS5zYW1w",
            "bGUudW5pdHkuQ29tcG9uZW50SWRlbnRpZmllclIJY29tcG9uZW50IqgIChtI",
            "REFkZGl0aW9uYWxMaWdodERhdGFVcGRhdGUSRQoJY29tcG9uZW50GAEgASgL",
            "MicucGx1bWUuc2FtcGxlLnVuaXR5LkNvbXBvbmVudElkZW50aWZpZXJSCWNv",
            "bXBvbmVudBIxChJpbnRlcmFjdHNfd2l0aF9za3kYAiABKAhIAFIQaW50ZXJh",
            "Y3RzV2l0aFNreYgBARIqCg5hZmZlY3RfZGlmZnVzZRgDIAEoCEgBUg1hZmZl",
            "Y3REaWZmdXNliAEBEiwKD2FmZmVjdF9zcGVjdWxhchgEIAEoCEgCUg5hZmZl",
            "Y3RTcGVjdWxhcogBARIyChJhZmZlY3RzX3ZvbHVtZXRyaWMYBSABKAhIA1IR",
            "YWZmZWN0c1ZvbHVtZXRyaWOIAQESJgoMbGlnaHRfZGltbWVyGAYgASgCSARS",
            "C2xpZ2h0RGltbWVyiAEBEjAKEXZvbHVtZXRyaWNfZGltbWVyGAcgASgCSAVS",
            "EHZvbHVtZXRyaWNEaW1tZXKIAQESKAoNc2hhZG93X2RpbW1lchgIIAEoAkgG",
            "UgxzaGFkb3dEaW1tZXKIAQESPQoYdm9sdW1ldHJpY19zaGFkb3dfZGltbWVy",
            "GAkgASgCSAdSFnZvbHVtZXRyaWNTaGFkb3dEaW1tZXKIAQESPQoYdm9sdW1l",
            "dHJpY19mYWRlX2Rpc3RhbmNlGAogASgCSAhSFnZvbHVtZXRyaWNGYWRlRGlz",
            "dGFuY2WIAQESJgoMc2hhcGVfcmFkaXVzGAsgASgCSAlSC3NoYXBlUmFkaXVz",
            "iAEBEjsKF2FwcGx5X3JhbmdlX2F0dGVudWF0aW9uGAwgASgISApSFWFwcGx5",
            "UmFuZ2VBdHRlbnVhdGlvbogBARJCCgxzdXJmYWNlX3RpbnQYDSABKAsyGi5w",
            "bHVtZS5zYW1wbGUuY29tbW9uLkNvbG9ySAtSC3N1cmZhY2VUaW50iAEBEkAK",
            "C3NoYWRvd190aW50GA4gASgLMhoucGx1bWUuc2FtcGxlLmNvbW1vbi5Db2xv",
            "ckgMUgpzaGFkb3dUaW50iAEBQhUKE19pbnRlcmFjdHNfd2l0aF9za3lCEQoP",
            "X2FmZmVjdF9kaWZmdXNlQhIKEF9hZmZlY3Rfc3BlY3VsYXJCFQoTX2FmZmVj",
            "dHNfdm9sdW1ldHJpY0IPCg1fbGlnaHRfZGltbWVyQhQKEl92b2x1bWV0cmlj",
            "X2RpbW1lckIQCg5fc2hhZG93X2RpbW1lckIbChlfdm9sdW1ldHJpY19zaGFk",
            "b3dfZGltbWVyQhsKGV92b2x1bWV0cmljX2ZhZGVfZGlzdGFuY2VCDwoNX3No",
            "YXBlX3JhZGl1c0IaChhfYXBwbHlfcmFuZ2VfYXR0ZW51YXRpb25CDwoNX3N1",
            "cmZhY2VfdGludEIOCgxfc2hhZG93X3RpbnRCGqoCF1BMVU1FLlNhbXBsZS5V",
            "bml0eS5IRFJQYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PLUME.Sample.Unity.IdentifiersReflection.Descriptor, global::PLUME.Sample.Common.ColorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataCreate), global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataCreate.Parser, new[]{ "Component" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataDestroy), global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataDestroy.Parser, new[]{ "Component" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataUpdate), global::PLUME.Sample.Unity.HDRP.HDAdditionalLightDataUpdate.Parser, new[]{ "Component", "InteractsWithSky", "AffectDiffuse", "AffectSpecular", "AffectsVolumetric", "LightDimmer", "VolumetricDimmer", "ShadowDimmer", "VolumetricShadowDimmer", "VolumetricFadeDistance", "ShapeRadius", "ApplyRangeAttenuation", "SurfaceTint", "ShadowTint" }, new[]{ "InteractsWithSky", "AffectDiffuse", "AffectSpecular", "AffectsVolumetric", "LightDimmer", "VolumetricDimmer", "ShadowDimmer", "VolumetricShadowDimmer", "VolumetricFadeDistance", "ShapeRadius", "ApplyRangeAttenuation", "SurfaceTint", "ShadowTint" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HDAdditionalLightDataCreate : pb::IMessage<HDAdditionalLightDataCreate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HDAdditionalLightDataCreate> _parser = new pb::MessageParser<HDAdditionalLightDataCreate>(() => new HDAdditionalLightDataCreate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HDAdditionalLightDataCreate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.HDRP.AdditionalLightDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataCreate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataCreate(HDAdditionalLightDataCreate other) : this() {
      component_ = other.component_ != null ? other.component_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataCreate Clone() {
      return new HDAdditionalLightDataCreate(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HDAdditionalLightDataCreate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HDAdditionalLightDataCreate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HDAdditionalLightDataCreate other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HDAdditionalLightDataDestroy : pb::IMessage<HDAdditionalLightDataDestroy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HDAdditionalLightDataDestroy> _parser = new pb::MessageParser<HDAdditionalLightDataDestroy>(() => new HDAdditionalLightDataDestroy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HDAdditionalLightDataDestroy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.HDRP.AdditionalLightDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataDestroy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataDestroy(HDAdditionalLightDataDestroy other) : this() {
      component_ = other.component_ != null ? other.component_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataDestroy Clone() {
      return new HDAdditionalLightDataDestroy(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HDAdditionalLightDataDestroy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HDAdditionalLightDataDestroy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HDAdditionalLightDataDestroy other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Mirrors UnityEngine.Rendering.HighDefinition.HDAdditionalLightData.
  /// Only HDRP-specific light data lives here. Intensity, light unit, color, color
  /// temperature and range are on the core UnityEngine.Light component (recorded by
  /// the core Light module) — HDRP reads them from there (legacyLight.intensity /
  /// legacyLight.lightUnit).
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HDAdditionalLightDataUpdate : pb::IMessage<HDAdditionalLightDataUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HDAdditionalLightDataUpdate> _parser = new pb::MessageParser<HDAdditionalLightDataUpdate>(() => new HDAdditionalLightDataUpdate());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HDAdditionalLightDataUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLUME.Sample.Unity.HDRP.AdditionalLightDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataUpdate(HDAdditionalLightDataUpdate other) : this() {
      _hasBits0 = other._hasBits0;
      component_ = other.component_ != null ? other.component_.Clone() : null;
      interactsWithSky_ = other.interactsWithSky_;
      affectDiffuse_ = other.affectDiffuse_;
      affectSpecular_ = other.affectSpecular_;
      affectsVolumetric_ = other.affectsVolumetric_;
      lightDimmer_ = other.lightDimmer_;
      volumetricDimmer_ = other.volumetricDimmer_;
      shadowDimmer_ = other.shadowDimmer_;
      volumetricShadowDimmer_ = other.volumetricShadowDimmer_;
      volumetricFadeDistance_ = other.volumetricFadeDistance_;
      shapeRadius_ = other.shapeRadius_;
      applyRangeAttenuation_ = other.applyRangeAttenuation_;
      surfaceTint_ = other.surfaceTint_ != null ? other.surfaceTint_.Clone() : null;
      shadowTint_ = other.shadowTint_ != null ? other.shadowTint_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HDAdditionalLightDataUpdate Clone() {
      return new HDAdditionalLightDataUpdate(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private global::PLUME.Sample.Unity.ComponentIdentifier component_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Unity.ComponentIdentifier Component {
      get { return component_; }
      set {
        component_ = value;
      }
    }

    /// <summary>Field number for the "interacts_with_sky" field.</summary>
    public const int InteractsWithSkyFieldNumber = 2;
    private readonly static bool InteractsWithSkyDefaultValue = false;

    private bool interactsWithSky_;
    /// <summary>
    /// drives Physically Based Sky
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool InteractsWithSky {
      get { if ((_hasBits0 & 1) != 0) { return interactsWithSky_; } else { return InteractsWithSkyDefaultValue; } }
      set {
        _hasBits0 |= 1;
        interactsWithSky_ = value;
      }
    }
    /// <summary>Gets whether the "interacts_with_sky" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInteractsWithSky {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "interacts_with_sky" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInteractsWithSky() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "affect_diffuse" field.</summary>
    public const int AffectDiffuseFieldNumber = 3;
    private readonly static bool AffectDiffuseDefaultValue = false;

    private bool affectDiffuse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AffectDiffuse {
      get { if ((_hasBits0 & 2) != 0) { return affectDiffuse_; } else { return AffectDiffuseDefaultValue; } }
      set {
        _hasBits0 |= 2;
        affectDiffuse_ = value;
      }
    }
    /// <summary>Gets whether the "affect_diffuse" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAffectDiffuse {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "affect_diffuse" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAffectDiffuse() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "affect_specular" field.</summary>
    public const int AffectSpecularFieldNumber = 4;
    private readonly static bool AffectSpecularDefaultValue = false;

    private bool affectSpecular_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AffectSpecular {
      get { if ((_hasBits0 & 4) != 0) { return affectSpecular_; } else { return AffectSpecularDefaultValue; } }
      set {
        _hasBits0 |= 4;
        affectSpecular_ = value;
      }
    }
    /// <summary>Gets whether the "affect_specular" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAffectSpecular {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "affect_specular" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAffectSpecular() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "affects_volumetric" field.</summary>
    public const int AffectsVolumetricFieldNumber = 5;
    private readonly static bool AffectsVolumetricDefaultValue = false;

    private bool affectsVolumetric_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AffectsVolumetric {
      get { if ((_hasBits0 & 8) != 0) { return affectsVolumetric_; } else { return AffectsVolumetricDefaultValue; } }
      set {
        _hasBits0 |= 8;
        affectsVolumetric_ = value;
      }
    }
    /// <summary>Gets whether the "affects_volumetric" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAffectsVolumetric {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "affects_volumetric" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAffectsVolumetric() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "light_dimmer" field.</summary>
    public const int LightDimmerFieldNumber = 6;
    private readonly static float LightDimmerDefaultValue = 0F;

    private float lightDimmer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float LightDimmer {
      get { if ((_hasBits0 & 16) != 0) { return lightDimmer_; } else { return LightDimmerDefaultValue; } }
      set {
        _hasBits0 |= 16;
        lightDimmer_ = value;
      }
    }
    /// <summary>Gets whether the "light_dimmer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLightDimmer {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "light_dimmer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLightDimmer() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "volumetric_dimmer" field.</summary>
    public const int VolumetricDimmerFieldNumber = 7;
    private readonly static float VolumetricDimmerDefaultValue = 0F;

    private float volumetricDimmer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VolumetricDimmer {
      get { if ((_hasBits0 & 32) != 0) { return volumetricDimmer_; } else { return VolumetricDimmerDefaultValue; } }
      set {
        _hasBits0 |= 32;
        volumetricDimmer_ = value;
      }
    }
    /// <summary>Gets whether the "volumetric_dimmer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolumetricDimmer {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "volumetric_dimmer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolumetricDimmer() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "shadow_dimmer" field.</summary>
    public const int ShadowDimmerFieldNumber = 8;
    private readonly static float ShadowDimmerDefaultValue = 0F;

    private float shadowDimmer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShadowDimmer {
      get { if ((_hasBits0 & 64) != 0) { return shadowDimmer_; } else { return ShadowDimmerDefaultValue; } }
      set {
        _hasBits0 |= 64;
        shadowDimmer_ = value;
      }
    }
    /// <summary>Gets whether the "shadow_dimmer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasShadowDimmer {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "shadow_dimmer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearShadowDimmer() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "volumetric_shadow_dimmer" field.</summary>
    public const int VolumetricShadowDimmerFieldNumber = 9;
    private readonly static float VolumetricShadowDimmerDefaultValue = 0F;

    private float volumetricShadowDimmer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VolumetricShadowDimmer {
      get { if ((_hasBits0 & 128) != 0) { return volumetricShadowDimmer_; } else { return VolumetricShadowDimmerDefaultValue; } }
      set {
        _hasBits0 |= 128;
        volumetricShadowDimmer_ = value;
      }
    }
    /// <summary>Gets whether the "volumetric_shadow_dimmer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolumetricShadowDimmer {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "volumetric_shadow_dimmer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolumetricShadowDimmer() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "volumetric_fade_distance" field.</summary>
    public const int VolumetricFadeDistanceFieldNumber = 10;
    private readonly static float VolumetricFadeDistanceDefaultValue = 0F;

    private float volumetricFadeDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VolumetricFadeDistance {
      get { if ((_hasBits0 & 256) != 0) { return volumetricFadeDistance_; } else { return VolumetricFadeDistanceDefaultValue; } }
      set {
        _hasBits0 |= 256;
        volumetricFadeDistance_ = value;
      }
    }
    /// <summary>Gets whether the "volumetric_fade_distance" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolumetricFadeDistance {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "volumetric_fade_distance" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolumetricFadeDistance() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "shape_radius" field.</summary>
    public const int ShapeRadiusFieldNumber = 11;
    private readonly static float ShapeRadiusDefaultValue = 0F;

    private float shapeRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShapeRadius {
      get { if ((_hasBits0 & 512) != 0) { return shapeRadius_; } else { return ShapeRadiusDefaultValue; } }
      set {
        _hasBits0 |= 512;
        shapeRadius_ = value;
      }
    }
    /// <summary>Gets whether the "shape_radius" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasShapeRadius {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "shape_radius" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearShapeRadius() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "apply_range_attenuation" field.</summary>
    public const int ApplyRangeAttenuationFieldNumber = 12;
    private readonly static bool ApplyRangeAttenuationDefaultValue = false;

    private bool applyRangeAttenuation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ApplyRangeAttenuation {
      get { if ((_hasBits0 & 1024) != 0) { return applyRangeAttenuation_; } else { return ApplyRangeAttenuationDefaultValue; } }
      set {
        _hasBits0 |= 1024;
        applyRangeAttenuation_ = value;
      }
    }
    /// <summary>Gets whether the "apply_range_attenuation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasApplyRangeAttenuation {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "apply_range_attenuation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearApplyRangeAttenuation() {
      _hasBits0 &= ~1024;
    }

    /// <summary>Field number for the "surface_tint" field.</summary>
    public const int SurfaceTintFieldNumber = 13;
    private global::PLUME.Sample.Common.Color surfaceTint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Color SurfaceTint {
      get { return surfaceTint_; }
      set {
        surfaceTint_ = value;
      }
    }

    /// <summary>Field number for the "shadow_tint" field.</summary>
    public const int ShadowTintFieldNumber = 14;
    private global::PLUME.Sample.Common.Color shadowTint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PLUME.Sample.Common.Color ShadowTint {
      get { return shadowTint_; }
      set {
        shadowTint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HDAdditionalLightDataUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HDAdditionalLightDataUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Component, other.Component)) return false;
      if (InteractsWithSky != other.InteractsWithSky) return false;
      if (AffectDiffuse != other.AffectDiffuse) return false;
      if (AffectSpecular != other.AffectSpecular) return false;
      if (AffectsVolumetric != other.AffectsVolumetric) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LightDimmer, other.LightDimmer)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VolumetricDimmer, other.VolumetricDimmer)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShadowDimmer, other.ShadowDimmer)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VolumetricShadowDimmer, other.VolumetricShadowDimmer)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VolumetricFadeDistance, other.VolumetricFadeDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShapeRadius, other.ShapeRadius)) return false;
      if (ApplyRangeAttenuation != other.ApplyRangeAttenuation) return false;
      if (!object.Equals(SurfaceTint, other.SurfaceTint)) return false;
      if (!object.Equals(ShadowTint, other.ShadowTint)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (component_ != null) hash ^= Component.GetHashCode();
      if (HasInteractsWithSky) hash ^= InteractsWithSky.GetHashCode();
      if (HasAffectDiffuse) hash ^= AffectDiffuse.GetHashCode();
      if (HasAffectSpecular) hash ^= AffectSpecular.GetHashCode();
      if (HasAffectsVolumetric) hash ^= AffectsVolumetric.GetHashCode();
      if (HasLightDimmer) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LightDimmer);
      if (HasVolumetricDimmer) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VolumetricDimmer);
      if (HasShadowDimmer) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShadowDimmer);
      if (HasVolumetricShadowDimmer) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VolumetricShadowDimmer);
      if (HasVolumetricFadeDistance) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VolumetricFadeDistance);
      if (HasShapeRadius) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShapeRadius);
      if (HasApplyRangeAttenuation) hash ^= ApplyRangeAttenuation.GetHashCode();
      if (surfaceTint_ != null) hash ^= SurfaceTint.GetHashCode();
      if (shadowTint_ != null) hash ^= ShadowTint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (HasInteractsWithSky) {
        output.WriteRawTag(16);
        output.WriteBool(InteractsWithSky);
      }
      if (HasAffectDiffuse) {
        output.WriteRawTag(24);
        output.WriteBool(AffectDiffuse);
      }
      if (HasAffectSpecular) {
        output.WriteRawTag(32);
        output.WriteBool(AffectSpecular);
      }
      if (HasAffectsVolumetric) {
        output.WriteRawTag(40);
        output.WriteBool(AffectsVolumetric);
      }
      if (HasLightDimmer) {
        output.WriteRawTag(53);
        output.WriteFloat(LightDimmer);
      }
      if (HasVolumetricDimmer) {
        output.WriteRawTag(61);
        output.WriteFloat(VolumetricDimmer);
      }
      if (HasShadowDimmer) {
        output.WriteRawTag(69);
        output.WriteFloat(ShadowDimmer);
      }
      if (HasVolumetricShadowDimmer) {
        output.WriteRawTag(77);
        output.WriteFloat(VolumetricShadowDimmer);
      }
      if (HasVolumetricFadeDistance) {
        output.WriteRawTag(85);
        output.WriteFloat(VolumetricFadeDistance);
      }
      if (HasShapeRadius) {
        output.WriteRawTag(93);
        output.WriteFloat(ShapeRadius);
      }
      if (HasApplyRangeAttenuation) {
        output.WriteRawTag(96);
        output.WriteBool(ApplyRangeAttenuation);
      }
      if (surfaceTint_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(SurfaceTint);
      }
      if (shadowTint_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(ShadowTint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (component_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Component);
      }
      if (HasInteractsWithSky) {
        output.WriteRawTag(16);
        output.WriteBool(InteractsWithSky);
      }
      if (HasAffectDiffuse) {
        output.WriteRawTag(24);
        output.WriteBool(AffectDiffuse);
      }
      if (HasAffectSpecular) {
        output.WriteRawTag(32);
        output.WriteBool(AffectSpecular);
      }
      if (HasAffectsVolumetric) {
        output.WriteRawTag(40);
        output.WriteBool(AffectsVolumetric);
      }
      if (HasLightDimmer) {
        output.WriteRawTag(53);
        output.WriteFloat(LightDimmer);
      }
      if (HasVolumetricDimmer) {
        output.WriteRawTag(61);
        output.WriteFloat(VolumetricDimmer);
      }
      if (HasShadowDimmer) {
        output.WriteRawTag(69);
        output.WriteFloat(ShadowDimmer);
      }
      if (HasVolumetricShadowDimmer) {
        output.WriteRawTag(77);
        output.WriteFloat(VolumetricShadowDimmer);
      }
      if (HasVolumetricFadeDistance) {
        output.WriteRawTag(85);
        output.WriteFloat(VolumetricFadeDistance);
      }
      if (HasShapeRadius) {
        output.WriteRawTag(93);
        output.WriteFloat(ShapeRadius);
      }
      if (HasApplyRangeAttenuation) {
        output.WriteRawTag(96);
        output.WriteBool(ApplyRangeAttenuation);
      }
      if (surfaceTint_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(SurfaceTint);
      }
      if (shadowTint_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(ShadowTint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (component_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Component);
      }
      if (HasInteractsWithSky) {
        size += 1 + 1;
      }
      if (HasAffectDiffuse) {
        size += 1 + 1;
      }
      if (HasAffectSpecular) {
        size += 1 + 1;
      }
      if (HasAffectsVolumetric) {
        size += 1 + 1;
      }
      if (HasLightDimmer) {
        size += 1 + 4;
      }
      if (HasVolumetricDimmer) {
        size += 1 + 4;
      }
      if (HasShadowDimmer) {
        size += 1 + 4;
      }
      if (HasVolumetricShadowDimmer) {
        size += 1 + 4;
      }
      if (HasVolumetricFadeDistance) {
        size += 1 + 4;
      }
      if (HasShapeRadius) {
        size += 1 + 4;
      }
      if (HasApplyRangeAttenuation) {
        size += 1 + 1;
      }
      if (surfaceTint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SurfaceTint);
      }
      if (shadowTint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowTint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HDAdditionalLightDataUpdate other) {
      if (other == null) {
        return;
      }
      if (other.component_ != null) {
        if (component_ == null) {
          Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
        }
        Component.MergeFrom(other.Component);
      }
      if (other.HasInteractsWithSky) {
        InteractsWithSky = other.InteractsWithSky;
      }
      if (other.HasAffectDiffuse) {
        AffectDiffuse = other.AffectDiffuse;
      }
      if (other.HasAffectSpecular) {
        AffectSpecular = other.AffectSpecular;
      }
      if (other.HasAffectsVolumetric) {
        AffectsVolumetric = other.AffectsVolumetric;
      }
      if (other.HasLightDimmer) {
        LightDimmer = other.LightDimmer;
      }
      if (other.HasVolumetricDimmer) {
        VolumetricDimmer = other.VolumetricDimmer;
      }
      if (other.HasShadowDimmer) {
        ShadowDimmer = other.ShadowDimmer;
      }
      if (other.HasVolumetricShadowDimmer) {
        VolumetricShadowDimmer = other.VolumetricShadowDimmer;
      }
      if (other.HasVolumetricFadeDistance) {
        VolumetricFadeDistance = other.VolumetricFadeDistance;
      }
      if (other.HasShapeRadius) {
        ShapeRadius = other.ShapeRadius;
      }
      if (other.HasApplyRangeAttenuation) {
        ApplyRangeAttenuation = other.ApplyRangeAttenuation;
      }
      if (other.surfaceTint_ != null) {
        if (surfaceTint_ == null) {
          SurfaceTint = new global::PLUME.Sample.Common.Color();
        }
        SurfaceTint.MergeFrom(other.SurfaceTint);
      }
      if (other.shadowTint_ != null) {
        if (shadowTint_ == null) {
          ShadowTint = new global::PLUME.Sample.Common.Color();
        }
        ShadowTint.MergeFrom(other.ShadowTint);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
          case 16: {
            InteractsWithSky = input.ReadBool();
            break;
          }
          case 24: {
            AffectDiffuse = input.ReadBool();
            break;
          }
          case 32: {
            AffectSpecular = input.ReadBool();
            break;
          }
          case 40: {
            AffectsVolumetric = input.ReadBool();
            break;
          }
          case 53: {
            LightDimmer = input.ReadFloat();
            break;
          }
          case 61: {
            VolumetricDimmer = input.ReadFloat();
            break;
          }
          case 69: {
            ShadowDimmer = input.ReadFloat();
            break;
          }
          case 77: {
            VolumetricShadowDimmer = input.ReadFloat();
            break;
          }
          case 85: {
            VolumetricFadeDistance = input.ReadFloat();
            break;
          }
          case 93: {
            ShapeRadius = input.ReadFloat();
            break;
          }
          case 96: {
            ApplyRangeAttenuation = input.ReadBool();
            break;
          }
          case 106: {
            if (surfaceTint_ == null) {
              SurfaceTint = new global::PLUME.Sample.Common.Color();
            }
            input.ReadMessage(SurfaceTint);
            break;
          }
          case 114: {
            if (shadowTint_ == null) {
              ShadowTint = new global::PLUME.Sample.Common.Color();
            }
            input.ReadMessage(ShadowTint);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (component_ == null) {
              Component = new global::PLUME.Sample.Unity.ComponentIdentifier();
            }
            input.ReadMessage(Component);
            break;
          }
          case 16: {
            InteractsWithSky = input.ReadBool();
            break;
          }
          case 24: {
            AffectDiffuse = input.ReadBool();
            break;
          }
          case 32: {
            AffectSpecular = input.ReadBool();
            break;
          }
          case 40: {
            AffectsVolumetric = input.ReadBool();
            break;
          }
          case 53: {
            LightDimmer = input.ReadFloat();
            break;
          }
          case 61: {
            VolumetricDimmer = input.ReadFloat();
            break;
          }
          case 69: {
            ShadowDimmer = input.ReadFloat();
            break;
          }
          case 77: {
            VolumetricShadowDimmer = input.ReadFloat();
            break;
          }
          case 85: {
            VolumetricFadeDistance = input.ReadFloat();
            break;
          }
          case 93: {
            ShapeRadius = input.ReadFloat();
            break;
          }
          case 96: {
            ApplyRangeAttenuation = input.ReadBool();
            break;
          }
          case 106: {
            if (surfaceTint_ == null) {
              SurfaceTint = new global::PLUME.Sample.Common.Color();
            }
            input.ReadMessage(SurfaceTint);
            break;
          }
          case 114: {
            if (shadowTint_ == null) {
              ShadowTint = new global::PLUME.Sample.Common.Color();
            }
            input.ReadMessage(ShadowTint);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
